:spawn:
  :frequency: 10
  :spritesheet_position:
    :x: 3
    :y: 0
  :collision_width: 10

  :max_health: 12
  :speed: 900

  :melee:
    :damage: !ruby/range 6..8

  :ranged_weapon:
     :type: :arrow
     :fire_chance: 0.01 # Per frame.

:lava_beetle:
  :frequency: 5
  :spritesheet_position:
    :x: 1
    :y: 0
  :collision_width: 20

  :max_health: 80
  :speed: 600

  :illumination_range: 1

  :melee:
    :damage: !ruby/range 15..25


:warrior:
  :frequency: 20
  :spritesheet_position:
    :x: 0
    :y: 0
  :collision_width: 14

  :max_health: 24
  :speed: 800

  :melee:
    :damage: !ruby/range 8..14


:skitter:
  :frequency: 5
  :spritesheet_position:
    :x: 2
    :y: 0
  :collision_width: 5

  :max_health: 1
  :speed: 1500

  :melee:
    :damage: !ruby/range 3..5