:goblin_archer:
  :frequency: 10

  :max_health: 10
  :speed: 6
  :scale: 0.6

  :melee:
    :damage: !ruby/range 1..2

  :ranged:
    :damage: !ruby/range 1..3
    :speed: 35
    :duration: 0.5
    :skirmish: !ruby/range 60..80
    :fire_chance: 0.01 # Per frame.


:ogre:
  :frequency: 5

  :max_health: 40
  :speed: 4
  :scale: 1.2

  :melee:
    :damage: !ruby/range 15..25


:orc:
  :frequency: 20

  :max_health: 18
  :speed: 8
  :scale: 0.9

  :melee:
    :damage: !ruby/range 4..7


:tick:
  :frequency: 5

  :max_health: 1
  :speed: 10
  :scale: 0.2

  :melee:
    :damage: !ruby/range 1..2