:spawn:
  :frequency: 10
  :spritesheet_position:
    :x: 3
    :y: 0
  :collision_width: 12

  :max_health: 12
  :speed: 9

  :melee:
    :damage: !ruby/range 6..8

  :ranged:
    :damage: !ruby/range 2..4
    :speed: 35
    :duration: 0.7
    :skirmish: !ruby/range 60..80
    :fire_chance: 0.01 # Per frame.


:lava_beetle:
  :frequency: 5
  :spritesheet_position:
    :x: 1
    :y: 0
  :collision_width: 14

  :max_health: 80
  :speed: 6

  :illumination_range: 1

  :melee:
    :damage: !ruby/range 15..25


:warrior:
  :frequency: 20
  :spritesheet_position:
    :x: 0
    :y: 0
  :collision_width: 14

  :max_health: 24
  :speed: 8

  :melee:
    :damage: !ruby/range 8..14


:skitter:
  :frequency: 5
  :spritesheet_position:
    :x: 2
    :y: 0
  :collision_width: 5

  :max_health: 1
  :speed: 15

  :melee:
    :damage: !ruby/range 3..5