:goblin_archer:
  :frequency: 10

  :health: 10
  :speed: 75
  :scale: 0.6

  :melee:
    :damage: 2

  :projectile:
    :damage: 2
    :speed: 35
    :duration: 0.5
    :fire_chance: 0.01 # Per frame.

:orc:
  :frequency: 20

  :health: 18
  :speed: 160
  :scale: 0.9

  :melee:
    :damage: 5

:ogre:
  :frequency: 5

  :health: 40
  :speed: 60
  :scale: 1.2

  :melee:
    :damage: 20