# Standard player primary weapon.
:zap:
  :cost:
    :energy: 4
  :damage: !ruby/range 5..15
  :speed: 1500
  :rotation_speed: 30
  :duration: 0.8
  :color: [0, 200, 200]

# Standard player secondary weapon.
:blast:
  :cost:
    :energy: 25
  :damage: !ruby/range 25..40
  :speed: 900
  :rotation_speed: 5
  :duration: 0.4
  :num_projectiles: 12
  :color: [0, 200, 200]

# Froglodyte spawn primary weapon.
:arrow:
  :cost: {}
  :damage: !ruby/range 2..4
  :speed: 800
  :duration: 0.9
  :skirmish_range: !ruby/range 60..90
  :color: [20, 20, 20]
